### ISSUE TITLE
腾讯云调用成功，但是返回数据事NULL，大佬给看看

### ISSUE THREAD

**Issue by RegisterID** [lxk0301/jd_scripts#103]
返回数据:

null

日志:

START RequestId: 4a02b5d1-6950-4bba-ae0d-a782cb654890

Event RequestId: 4a02b5d1-6950-4bba-ae0d-a782cb654890

2020-11-16T03:55:00.102Z 4a02b5d1-6950-4bba-ae0d-a782cb654890 jd_unsubscribe

2020-11-16T03:55:00.105Z 4a02b5d1-6950-4bba-ae0d-a782cb654890

🔔取关京东店铺和商品, 开始!

2020-11-16T03:55:00.106Z 7a9d6dd3-1924-4696-85d7-e9f6764c6faa (node:11) UnhandledPromiseRejectionWarning: Error: Cannot find module 'got'

Require stack:

- /var/user/jd_unsubscribe.js

- /var/user/index.js

- /var/runtime/node12/UserFunction.js

- /var/runtime/node12/Runtime.engine.js

- /var/runtime/node12/bootstrap.js

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)

    at Function.Module._load (internal/modules/cjs/loader.js:864:27)

    at Module.require (internal/modules/cjs/loader.js:1044:19)

    at require (internal/modules/cjs/helpers.js:77:18)

    at Object.initGotEnv (/var/user/jd_unsubscribe.js:334:3645)

    at Object.post (/var/user/jd_unsubscribe.js:334:5101)

    at /var/user/jd_unsubscribe.js:287:7

    at new Promise (<anonymous>)

    at TotalBean (/var/user/jd_unsubscribe.js:273:10)

    at /var/user/jd_unsubscribe.js:52:13

2020-11-16T03:55:00.107Z 7a9d6dd3-1924-4696-85d7-e9f6764c6faa (node:11) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)

 

END RequestId: 4a02b5d1-6950-4bba-ae0d-a782cb654890

Report RequestId: 4a02b5d1-6950-4bba-ae0d-a782cb654890 Duration:6ms Memory:64MB MemUsage:52.648438MB

**Comment by socalledPF** [comment]
node_modules 一起传上去了吗？

**Comment by RegisterID** [comment]
> node_modules 一起传上去了吗？

传了

**Comment by lxk0301** [comment]
没有got依赖包

**Comment by RegisterID** [comment]
> 没有got依赖包

大佬我运行了2个脚本显示成功，但是返回的数据还是null，有问题吗？

**Comment by RegisterID** [comment]
> 没有got依赖包

日志里显示脚本成功了，就是上面的返回数据是NULL，这个有问题吗？

**Comment by socalledPF** [comment]
你没写return 值就是null

**Comment by RegisterID** [comment]
> 你没写return 值就是null

请问return值是什么？必需要填吗？
