### ISSUE TITLE
京喜js错误-github action环境

### ISSUE THREAD

**Issue by ZedeX** [lxk0301/jd_scripts#114]
❗️京喜, 错误!
ReferenceError: doubleres is not defined
    at /home/runner/work/auto-workflow-JD.com-jdcoin/auto-workflow-JD.com-jdcoin/execute.js:200:24
    at new Promise (<anonymous>)
    at showmsg (/home/runner/work/auto-workflow-JD.com-jdcoin/auto-workflow-JD.com-jdcoin/execute.js:197:10)
    at /home/runner/work/auto-workflow-JD.com-jdcoin/auto-workflow-JD.com-jdcoin/execute.js:43:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

🔔京喜, 结束! 🕛 17.051 秒

![image](https://user-images.githubusercontent.com/394198/99473694-091a3100-2986-11eb-8c08-62fe3373f05b.png)

**Comment by lxk0301** [comment]
走错地方了吧你
