### ISSUE TITLE
云函数部分运行报错，其他运行正常

### ISSUE THREAD

**Issue by Sirius2s** [lxk0301/jd_scripts#132]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [x] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：用的action一键部署到腾讯云函数，有部分脚本运行报错，其他运行正常

### (2) 详细日志
A：
排行榜
2020-11-20T02:00:01 .209Z a47661 c6-3a06-40a4- 8230-90ec5a779469
!京东排行榜，错误!
ReferenceError: merge is not defined
at initial (eval at main (eval at <anonymous> (var/user/indexjs: 19: 13)). <anonymous>:
183:9)
at eval (eval at main (eval at <anonymous> (var/user/indexjs:19:13)). <anonymous>:
43:7)
at eval (eval at main (eval at <anonymous> (var/userindexjs: 19: 13)), <anonymous>:
55:3)
at main (eval at <anonymous> (var/user/indexjs: 19: 13)，<anonymous>:31:5)
at process TicksAndRejections (internal/process/task_ queuesjs:97:5)
2020-11-20T02:00:01 .209Z a47661 c6-3a06-40a4- 8230-90ec5a779469
京东排行榜，结束! O 0.001秒

摇钱树
2020-11-20T01:15:07 .598Z 5a1 b39ae-d25d-40c8-bb97-d9b264fda155
京东摇钱树，失败!原因: Error: EROFS: read-only file system, open "'var/user/box.dat!
2020-11-20T01:15:07 .599Z 5a1 b39ae-d25d-40c8-bb97-d9b264fda155
京东摇钱树,结束!O 7.175秒

种豆
2020-11-20T01:15:14 .494Z 5a1 b39ae-d25d-40c8-bb97-d9b264fda155
开始做逛逛会场任务
2020-11-20T01:15:14 .494Z 5a1b39ae-d25d-40c8-bb97-d9b264fda 155 
京东种豆得豆，失败!原因: TypeError: 'caller'. 'callee' , and 'arguments' properties may not be accessed on strict
mode functions or the arguments objects for calls to them! 
2020-11-20T01:15:14 .494Z 5a1b39ae-d25d-40c8-bb97-d9b264fda 155 
京东种豆得豆，结束!O 14.155秒

宠汪汪积分兑换奖品
2020-11-20T00:00:00. 550Z c772ddf-ffb0-4f41-b732- 9dd1 5be8f90e
宠汪汪积分兑换奖品，失败!原因: ReferenceError: message is not defined!
2020-11-20T00:00:00 .550Z c72ddf-ffb0-4f4 1-b732-9dd1 5be8f90e
宠汪汪积分兑换奖品，结束! O 0.143秒

萌宠
2020-11-19T22:05:03 .944Z 7211f495-caa5-4903-823a-bf9f1 bbd2f6f开始任务初始化
2020-11-19T22:05:03 .944Z 7211f495-caa5-4903-823a- bf9f1 bbd2f6f
东东萌宠，失败!原因: TypeError: 'caller'. 'callee' , and 'arguments' properties may not be accessed on strict
mode functions or the arguments objects for caills to them!
2020-11-19T22:05:03 .944Z 7211f495-caa5-4903-823a- bf9f1 bbd2f6f
东东萌宠，结束! O 3.531秒

农场
2020-11-19T22:05:33.671Z 7211f495-caa5-4903-823a-bf9f1 bbd2f6f
初始化任务列表
2020-11-19T22:05:33.672Z 7211f495-caa5-4903-823a-bf9f1 bbd2f6f
东东农场,失败!原因: TypeError: 'caller', callee'. and 'arguments' properties may not be accessed on strict
mode functions or the arguments objects for calls to them!
2020-11-19T22:05:33.672Z 7211f495-caa5-4903-823a-bf9f1 bbd2f6f
东东农场,结束! O 33.252秒

全民开红包
2020-11-19T16:10:00.602Z ab82cf78-9895-4 136- bea7-5b2623e38e57
京东全民开红包，失败!原因: TypeError: 'caller'. 'callee'，and 'arguments' properties may not be accessed on strict
mode functions or the arguments objects for calls to them!
2020-11-19T16:10:00.603Z ab82cf78-9895-4 136- bea7-5b2623e38e57
京东全民开红包，结束! O 0.146秒

取关京东店铺和商品
2020-11-19T16:10:00.626Z ab82cf78-9895-4 136- bea7-5b2623e38e57
取关京东店铺和商品，失败!原因: ReferenceError: message is not defined!
2020-11-19T16:10:00.627Z ab82cf78-9895-4136-bea7-5b2623e38e57
取关京东店铺和商品,结束! O 0.14秒

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by YouHaveGone** [comment]
同样的错误

> 2020-11-20T03:12:00.639Z 3d8515d4-c018-4c0a-8bd2-41a9ba7e8118
> ❌ 天天提鹅, 失败! 原因: ReferenceError: message is not defined!

> 2020-11-20T03:12:00.801Z 3d8515d4-c018-4c0a-8bd2-41a9ba7e8118
> ❌ 金融养猪, 失败! 原因: ReferenceError: message is not defined!

> ❌ 东东农场, 失败! 原因: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them!

**Comment by iouAkira** [comment]
`index.js`  里面换成下面的执行本地 `js` 看看

```js
'use strict';
exports.main_handler = async (event, context, callback) => {
  try {
      //如果想在一个定时触发器里面执行多个js文件需要在定时触发器的【附加信息】里面填写对应的名称，用 & 链接
      //例如我想一个定时触发器里执行jd_speed.js和jd_bean_change.js，在定时触发器的【附加信息】里面就填写 jd_speed&jd_bean_change
      for (const v of event["Message"].split("&")) {
          console.log(v);
          delete require.cache[require.resolve('./'+v+'.js')];
          require('./'+v+'.js')
      }
   } catch (e) {
    console.error(e)
   }
}
```

**Comment by lxk0301** [comment]
`message is not defined!`  的问题已经解决、  其他的问题 截图看看你们的index.js

**Comment by Sirius2s** [comment]
![image](https://user-images.githubusercontent.com/53803920/99766248-ae2a3a80-2b3b-11eb-986d-c60e8fb13d4f.png)
一键部署出来的默认结果

**Comment by lxk0301** [comment]
你换成这个试试看吧

![image](https://user-images.githubusercontent.com/21308593/99766818-d8302c80-2b3c-11eb-9859-28f8eebdf519.png)

**Comment by Sirius2s** [comment]
我改index之前：
13:12:00养猪失败
![image](https://user-images.githubusercontent.com/53803920/99767697-6eb11d80-2b3e-11eb-8bfd-8e786ab4e8ad.png)
14:12:00养猪成功
![image](https://user-images.githubusercontent.com/53803920/99767778-8c7e8280-2b3e-11eb-8928-3b0176cb2e1f.png)

**Comment by misnaya** [comment]
> `index.js` 里面换成下面的执行本地 `js` 看看
> 
> ```js
> 'use strict';
> exports.main_handler = async (event, context, callback) => {
>   try {
>       //如果想在一个定时触发器里面执行多个js文件需要在定时触发器的【附加信息】里面填写对应的名称，用 & 链接
>       //例如我想一个定时触发器里执行jd_speed.js和jd_bean_change.js，在定时触发器的【附加信息】里面就填写 jd_speed&jd_bean_change
>       for (const v of event["Message"].split("&")) {
>           console.log(v);
>           delete require.cache[require.resolve('./'+v+'.js')];
>           require('./'+v+'.js')
>       }
>    } catch (e) {
>     console.error(e)
>    }
> }
> ```

emm  改为本地js文件测试是可以跑过的 ，但是不管是github还是gitee  测试都报错

**Comment by Sirius2s** [comment]
> 我改index(14:35:58)之前：
> 13:12:00养猪失败
> ![image](https://user-images.githubusercontent.com/53803920/99767697-6eb11d80-2b3e-11eb-8bfd-8e786ab4e8ad.png)
> 14:12:00养猪成功
> ![image](https://user-images.githubusercontent.com/53803920/99767778-8c7e8280-2b3e-11eb-8928-3b0176cb2e1f.png)
这个期间内刚好远端代码调整了

**Comment by snakeJohn** [comment]
{
  "key1": "test value 1",
  "key2": "test value 2"
}
执行摘要测试成功
请求ID	
05498b20-d2d3-4c44-a6ba-55ac33a76633
运行时间	
1ms
计费时间	
1ms
运行内存	
69.99608993530273MB
返回结果

Text
null

执行日志

UTF-8
START RequestId: 05498b20-d2d3-4c44-a6ba-55ac33a76633

Event RequestId: 05498b20-d2d3-4c44-a6ba-55ac33a76633

2020-11-20T11:51:23.413Z  05498b20-d2d3-4c44-a6ba-55ac33a76633  TypeError: Cannot read property 'split' of undefined

    at Runtime.exports.main_handler [as handler] (/var/user/index.js:6:40)

    at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:215:23)

    at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:55:12)

    at listOnTimeout (internal/timers.js:549:17)

    at processTimers (internal/timers.js:492:7)

 

END RequestId: 05498b20-d2d3-4c44-a6ba-55ac33a76633

Report RequestId: 05498b20-d2d3-4c44-a6ba-55ac33a76633 Duration:1ms Memory:128MB MemUsage:69.996094MB

**Comment by snakeJohn** [comment]
测试报错

**Comment by iouAkira** [comment]
> 测试报错
看wiki测试
https://github.com/lxk0301/jd_scripts/wiki/TencentSCF#224-%E6%9F%A5%E7%9C%8B%E5%92%8C%E6%B5%8B%E8%AF%95

**Comment by snakeJohn** [comment]
测试没问题，但是我看了一下日志，四个调用失败都是下面的报错信息。。。。请大佬帮忙看一下，谢谢



返回数据:

{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"TypeError: Cannot read property 'body' of undefined\n    at Request._callback (/var/user/index.js:19:27)\n    at self.callback (/var/user/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:311:20)\n    at Request.onRequestError (/var/user/node_modules/request/request.js:877:8)\n    at ClientRequest.emit (events.js:311:20)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:311:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"}

日志:

START RequestId: baf53814-a1e3-42d1-b378-15830f54019d

Event RequestId: baf53814-a1e3-42d1-b378-15830f54019d

2020-11-20T12:15:01.235Z baf53814-a1e3-42d1-b378-15830f54019d jd_joy_feedPets

2020-11-20T12:15:01.235Z baf53814-a1e3-42d1-b378-15830f54019d jd_joy

2020-11-20T12:15:01.236Z baf53814-a1e3-42d1-b378-15830f54019d jd_moneyTree

2020-11-20T12:15:01.236Z baf53814-a1e3-42d1-b378-15830f54019d jd_plantBean

 

ERROR RequestId:baf53814-a1e3-42d1-b378-15830f54019d Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"TypeError: Cannot read property 'body' of undefined\n    at Request._callback (/var/user/index.js:19:27)\n    at self.callback (/var/user/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:311:20)\n    at Request.onRequestError (/var/user/node_modules/request/request.js:877:8)\n    at ClientRequest.emit (events.js:311:20)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:311:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"} 

END RequestId: baf53814-a1e3-42d1-b378-15830f54019d

Report RequestId: baf53814-a1e3-42d1-b378-15830f54019d Duration:28ms Memory:128MB MemUsage:20.574219MB

**Comment by iouAkira** [comment]
> 测试没问题，但是我看了一下日志，四个调用失败都是下面的报错信息。。。。请大佬帮忙看一下，谢谢
> 
> 
> 
> 
> 
> 
> 
> 返回数据:
> 
> 
> 
> {"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"TypeError: Cannot read property 'body' of undefined\n    at Request._callback (/var/user/index.js:19:27)\n    at self.callback (/var/user/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:311:20)\n    at Request.onRequestError (/var/user/node_modules/request/request.js:877:8)\n    at ClientRequest.emit (events.js:311:20)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:311:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"}
> 
> 
> 
> 日志:
> 
> 
> 
> START RequestId: baf53814-a1e3-42d1-b378-15830f54019d
> 
> 
> 
> Event RequestId: baf53814-a1e3-42d1-b378-15830f54019d
> 
> 
> 
> 2020-11-20T12:15:01.235Z baf53814-a1e3-42d1-b378-15830f54019d jd_joy_feedPets
> 
> 
> 
> 2020-11-20T12:15:01.235Z baf53814-a1e3-42d1-b378-15830f54019d jd_joy
> 
> 
> 
> 2020-11-20T12:15:01.236Z baf53814-a1e3-42d1-b378-15830f54019d jd_moneyTree
> 
> 
> 
> 2020-11-20T12:15:01.236Z baf53814-a1e3-42d1-b378-15830f54019d jd_plantBean
> 
> 
> 
>  
> 
> 
> 
> ERROR RequestId:baf53814-a1e3-42d1-b378-15830f54019d Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"TypeError: Cannot read property 'body' of undefined\n    at Request._callback (/var/user/index.js:19:27)\n    at self.callback (/var/user/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:311:20)\n    at Request.onRequestError (/var/user/node_modules/request/request.js:877:8)\n    at ClientRequest.emit (events.js:311:20)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:311:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"} 
> 
> 
> 
> END RequestId: baf53814-a1e3-42d1-b378-15830f54019d
> 
> 
> 
> Report RequestId: baf53814-a1e3-42d1-b378-15830f54019d Duration:28ms Memory:128MB MemUsage:20.574219MB
> 
> 
> 
> 

往上翻，换成执行本地试试，或者同步一下最新代码在部署一次

**Comment by snakeJohn** [comment]
> > 测试没问题，但是我看了一下日志，四个调用失败都是下面的报错信息。。。。请大佬帮忙看一下，谢谢
> > 返回数据:
> > {"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"TypeError: Cannot read property 'body' of undefined\n    at Request._callback (/var/user/index.js:19:27)\n    at self.callback (/var/user/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:311:20)\n    at Request.onRequestError (/var/user/node_modules/request/request.js:877:8)\n    at ClientRequest.emit (events.js:311:20)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:311:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"}
> > 日志:
> > START RequestId: baf53814-a1e3-42d1-b378-15830f54019d
> > Event RequestId: baf53814-a1e3-42d1-b378-15830f54019d
> > 2020-11-20T12:15:01.235Z baf53814-a1e3-42d1-b378-15830f54019d jd_joy_feedPets
> > 2020-11-20T12:15:01.235Z baf53814-a1e3-42d1-b378-15830f54019d jd_joy
> > 2020-11-20T12:15:01.236Z baf53814-a1e3-42d1-b378-15830f54019d jd_moneyTree
> > 2020-11-20T12:15:01.236Z baf53814-a1e3-42d1-b378-15830f54019d jd_plantBean
> > ERROR RequestId:baf53814-a1e3-42d1-b378-15830f54019d Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"TypeError: Cannot read property 'body' of undefined\n    at Request._callback (/var/user/index.js:19:27)\n    at self.callback (/var/user/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:311:20)\n    at Request.onRequestError (/var/user/node_modules/request/request.js:877:8)\n    at ClientRequest.emit (events.js:311:20)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:311:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"}
> > END RequestId: baf53814-a1e3-42d1-b378-15830f54019d
> > Report RequestId: baf53814-a1e3-42d1-b378-15830f54019d Duration:28ms Memory:128MB MemUsage:20.574219MB
> 
> 往上翻，换成执行本地试试，或者同步一下最新代码在部署一次

好的，我等他自动执行看看。谢谢

**Comment by Sirius2s** [comment]
已改本地运行。提示如下
2020-11-21T05:15:07.298Z	c3102e96-3285-4155-ae71-3c790b7ab840

❌ 京东摇钱树, 失败! 原因: Error: EROFS: read-only file system, open '/var/user/box.dat'!

**Comment by lxk0301** [comment]
> 已改本地运行。提示如下
> 2020-11-21T05:15:07.298Z c3102e96-3285-4155-ae71-3c790b7ab840
> 
> ❌ 京东摇钱树, 失败! 原因: Error: EROFS: read-only file system, open '/var/user/box.dat'!

脚本不是最新的

**Comment by lxk0301** [comment]
> 同样的错误
> 
> > 2020-11-20T03:12:00.639Z 3d8515d4-c018-4c0a-8bd2-41a9ba7e8118
> > ❌ 天天提鹅, 失败! 原因: ReferenceError: message is not defined!
> 
> > 2020-11-20T03:12:00.801Z 3d8515d4-c018-4c0a-8bd2-41a9ba7e8118
> > ❌ 金融养猪, 失败! 原因: ReferenceError: message is not defined!
> 
> > ❌ 东东农场, 失败! 原因: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them!

像农场和萌宠这种错误提示

把index.js里面的'use strict';删掉试试

**Comment by Sirius2s** [comment]
2020-11-23T00:12:01.308Z 27585454-83d2-41e6-8c20-63f95ba13f0d

❌ 京喜工厂, 失败! 原因: ReferenceError: goodsUrl is not defined!

2020-11-23T00:12:01.308Z 27585454-83d2-41e6-8c20-63f95ba13f0d

🔔京喜工厂, 结束! 🕛 0.146 秒

**Comment by Sirius2s** [comment]
> > 同样的错误
> > > 2020-11-20T03:12:00.639Z 3d8515d4-c018-4c0a-8bd2-41a9ba7e8118
> > > x 天天提鹅, 失败! 原因: ReferenceError: message is not defined!
> > 
> > 
> > > 2020-11-20T03:12:00.801Z 3d8515d4-c018-4c0a-8bd2-41a9ba7e8118
> > > x 金融养猪, 失败! 原因: ReferenceError: message is not defined!
> > 
> > 
> > > x 东东农场, 失败! 原因: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them!
> 
> 像农场和萌宠这种错误提示
> 
> 把index.js里面的'use strict';删掉试试

**确认可行**(_京喜工厂提示goodsUrl is not defined的，这个修改也同样有效_)：
修改后
2020-11-23T01:17:02.032Z a8bda093-f906-422a-acbd-e7ebe34715c1
🔔京东种豆得豆, 结束! 🕛 121.682 秒

**09:11:09修改**

修改前
2020-11-23T00:15:12.571Z 437d5d85-addd-4237-ae82-64a32b57ba49
❌ 京东种豆得豆, 失败! 原因: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them!
2020-11-23T00:15:12.571Z 437d5d85-addd-4237-ae82-64a32b57ba49
🔔京东种豆得豆, 结束! 🕛 12.181 秒

**Comment by Sirius2s** [comment]
ERROR RequestId:6717989a-5e28-4931-9347-59de0cbc54eb Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"TypeError: Cannot read property 'body' of undefined\n

出现上述提示的或其他"不服"的，请改为方法1本地运行。如下
//'use strict';
exports.main_handler = async (event, context, callback) => {
  try {
      //如果想在一个定时触发器里面执行多个js文件需要在定时触发器的【附加信息】里面填写对应的名称，用 & 链接
      //例如我想一个定时触发器里执行jd_speed.js和jd_bean_change.js，在定时触发器的【附加信息】里面就填写 jd_speed&jd_bean_change
      for (const v of event["Message"].split("&")) {
          console.log(v);
          ///var request = require('request');
          //1.执行自己上传的js文件
          delete require.cache[require.resolve('./'+v+'.js')];
          require('./'+v+'.js')
        
          //2.执行国内gitee远端js文件如果部署，在国内节点，选择1或2的方式
          //request('https://gitee.com/lxk0301/jd_scripts/raw/master/'+v+'.js', function (error, response, body) {
          //    eval(response.body)
          //})

          //3.执行github远端的js文件
          ///request('https://raw.githubusercontent.com/lxk0301/jd_scripts/master/'+v+'.js', function (error, response, body) {
          ///  eval(response.body)
          ///})  
      }
   } catch (e) {
    console.error(e)
   }
}
