### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Error: Cannot find module 'got'

### ISSUE THREAD

**Issue by yks176175** [lxk0301/jd_scripts#178]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [x] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：
调用成功显示成功，显示找不到“got”模块
### (2) 详细日志
A：
START RequestId: b6d0fe50-76ee-4205-b380-02f78f3fd4d9

Event RequestId: b6d0fe50-76ee-4205-b380-02f78f3fd4d9

2020-11-25T21:15:01.733Z b6d0fe50-76ee-4205-b380-02f78f3fd4d9 jd_joy_feedPets

2020-11-25T21:15:02.447Z b6d0fe50-76ee-4205-b380-02f78f3fd4d9 jd_joy

2020-11-25T21:15:02.447Z b6d0fe50-76ee-4205-b380-02f78f3fd4d9 jd_moneyTree

2020-11-25T21:15:02.447Z b6d0fe50-76ee-4205-b380-02f78f3fd4d9 jd_plantBean

2020-11-25T21:15:02.447Z b6d0fe50-76ee-4205-b380-02f78f3fd4d9 jd_dreamFactory

2020-11-25T21:15:02.492Z b6d0fe50-76ee-4205-b380-02f78f3fd4d9

🔔宠汪汪, 开始!

2020-11-25T21:15:02.497Z b6d0fe50-76ee-4205-b380-02f78f3fd4d9 (node:11) UnhandledPromiseRejectionWarning: Error: Cannot find module 'got'

Require stack:

- /var/user/index.js

- /var/runtime/node12/UserFunction.js

- /var/runtime/node12/Runtime.engine.js

- /var/runtime/node12/bootstrap.js

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)

    at Function.Module._load (internal/modules/cjs/loader.js:864:27)

    at Module.require (internal/modules/cjs/loader.js:1044:19)

    at require (internal/modules/cjs/helpers.js:77:18)

    at Object.initGotEnv (eval at <anonymous> (/var/user/index.js:20:13), <anonymous>:757:3645)

    at Object.post (eval at <anonymous> (/var/user/index.js:20:13), <anonymous>:757:5101)

    at eval (eval at <anonymous> (/var/user/index.js:20:13), <anonymous>:699:7)

    at new Promise (<anonymous>)

    at TotalBean (eval at <anonymous> (/var/user/index.js:20:13), <anonymous>:685:10)

    at eval (eval at <anonymous> (/var/user/index.js:20:13), <anonymous>:58:13)

2020-11-25T21:15:02.497Z b6d0fe50-76ee-4205-b380-02f78f3fd4d9 (node:11) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

2020-11-25T21:15:02.497Z b6d0fe50-76ee-4205-b380-02f78f3fd4d9 (node:11) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

2020-11-25T21:15:02.502Z b6d0fe50-76ee-4205-b380-02f78f3fd4d9
![image](https://user-images.githubusercontent.com/67717024/100317552-85042100-2ff7-11eb-90b7-f59bda70eb0e.png)

### (1) Node.js版本

A：
node：12.16
### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
请提供npm install日志

**Comment by yks176175** [comment]
有一布做错了，重新做了一遍就好了
