### ISSUE TITLE
自己上传仓库，添加yml文件后，设置action运行报错。提示找不到XXX.js

### ISSUE THREAD

**Issue by sgzman** [lxk0301/jd_scripts#19]
Error: Cannot find module '/home/runner/work/my_jd_scripts/my_jd_scripts/jd_collectProduceScore.js'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
at Function.Module._load (internal/modules/cjs/loader.js:725:27)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
at internal/main/run_main_module.js:17:47 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}
Error: Process completed with exit code 1.

**Comment by sgzman** [comment]
已解决
