### ISSUE TITLE
腾讯云函数运行报错，实际无运行成功

### ISSUE THREAD

**Issue by myDawn** [lxk0301/jd_scripts#26]
![image](https://user-images.githubusercontent.com/16184224/98636093-22f1bd80-2361-11eb-94fc-902632934a3b.png)
报错信息：❌ 东东农场, 失败! 原因: Error: EROFS: read-only file system, open '/var/user/box.dat'!

求指导

**Comment by lxk0301** [comment]
腾讯云函数没有写入权限

**Comment by leecheng311** [comment]
同这个问题，是要做什么操作么

**Comment by lxk0301** [comment]
最新脚本已做兼容

**Comment by ykrank** [comment]
> 最新脚本已做兼容

Error: EROFS: read-only file system, open 'JD_DailyBonus.js
签到也需要兼容

**Comment by lxk0301** [comment]
@ykrank 京豆签到无法兼容。

**Comment by Kirietoan** [comment]
> @ykrank 京豆签到无法兼容。

这个没办法解决吗？

**Comment by ykrank** [comment]
> > @ykrank 京豆签到无法兼容。
> 
> 这个没办法解决吗？

自己把JD_DailyBonus.js 下载下来，然后改一下调用应该可以吧

**Comment by Kirietoan** [comment]
> > > @ykrank 京豆签到无法兼容。
> > 
> > 
> > 这个没办法解决吗？
> 
> 自己把JD_DailyBonus.js 下载下来，然后改一下调用应该可以吧

请问调用怎么改呢？您那边成功了吗？

**Comment by ykrank** [comment]
> @ykrank 京豆签到无法兼容。

有个兼容方法，将文件写在tmp文件夹。我本来考虑自己改，不过你这边直接做兼容应该是最好的。

环境内有可写空间吗？
有。云函数在执行过程中，都拥有一块500MB的临时磁盘空间 /tmp，用户可以在执行代码时对该空间进行一些读写操作，也可以创建子目录，但这部分数据在函数执行完成后不会保留。
说明：
实例间的临时空间互相隔离，不共享，即每个实例均有独立的临时空间。
运行环境内除 /tmp 目录下，其他均限制为只读。

**Comment by ykrank** [comment]
而且这个文件夹还不用清理

**Comment by lxk0301** [comment]
@ykrank 原来如此。那倒是可以解决。

**Comment by DoveBoy** [comment]
@ykrank 具体怎么操作呢？

**Comment by lxk0301** [comment]
> 而且这个文件夹还不用清理

云函数把下载的路径和写入路径都改成了再tmp里面。还是有问题

![C3604722-DCA2-4B86-A546-5FAC5A5D7FAA](https://user-images.githubusercontent.com/21308593/98898013-a5a48500-24e7-11eb-9569-66915584b03f.jpeg)

**Comment by ykrank** [comment]
> > 而且这个文件夹还不用清理
> 
> 云函数把下载的路径和写入路径都改成了再tmp里面。还是有问题
> 
> ![C3604722-DCA2-4B86-A546-5FAC5A5D7FAA](https://user-images.githubusercontent.com/21308593/98898013-a5a48500-24e7-11eb-9569-66915584b03f.jpeg)

下面的代码和node命令里面的路径也要改吧，我看到下面的调用里面没有直接引用这里

**Comment by ykrank** [comment]
不过我遇到的问题是不知道怎么指定node版本

```
2020-11-12T06:11:23.028Z 309a0f45-97e5-4094-8d48-d8cc5087f7e4 ⚠⚠⚠⚠⚠⚠⚠⚠  如遇到Bark APP推送通知消息失败的,请换用其他通知方式,Bark对推送内容长度有限制  ⚠⚠⚠⚠⚠⚠⚠⚠⚠

2020-11-12T06:11:23.028Z 309a0f45-97e5-4094-8d48-d8cc5087f7e4 开始替换变量

2020-11-12T06:11:23.029Z 309a0f45-97e5-4094-8d48-d8cc5087f7e4 替换变量完毕

2020-11-12T06:11:23.030Z 309a0f45-97e5-4094-8d48-d8cc5087f7e4

开始执行脚本签到，请稍等

2020-11-12T06:11:23.422Z 309a0f45-97e5-4094-8d48-d8cc5087f7e4 <Buffer 2f 74 6d 70 2f 4a 44 5f 44 61 69 6c 79 42 6f 6e 75 73 2e 6a 73 3a 31 30 35 0a 61 73 79 6e 63 20 66 75 6e 63 74 69 6f 6e 20 61 6c 6c 28 29 20 7b 0a 20 ... 475 more bytes>

2020-11-12T06:11:23.423Z 309a0f45-97e5-4094-8d48-d8cc5087f7e4 京东签到脚本执行异常:Error: Command failed: node /tmp/JD_DailyBonus.js >> /tmp/result.txt

/tmp/JD_DailyBonus.js:105

async function all() {

      ^^^^^^^^

SyntaxError: Unexpected token function

    at createScript (vm.js:56:10)

    at Object.runInThisContext (vm.js:97:10)

    at Module._compile (module.js:549:28)

    at Object.Module._extensions..js (module.js:586:10)

    at Module.load (module.js:494:32)

    at tryModuleLoad (module.js:453:12)

    at Function.Module._load (module.js:445:3)

    at Module.runMain (module.js:611:10)

    at run (bootstrap_node.js:394:7)

    at startup (bootstrap_node.js:160:9)
```

**Comment by lxk0301** [comment]
> 不过我遇到的问题是不知道怎么指定node版本
> 
> ```
> 2020-11-12T06:11:23.028Z 309a0f45-97e5-4094-8d48-d8cc5087f7e4 ⚠⚠⚠⚠⚠⚠⚠⚠  如遇到Bark APP推送通知消息失败的,请换用其他通知方式,Bark对推送内容长度有限制  ⚠⚠⚠⚠⚠⚠⚠⚠⚠
> 
> 2020-11-12T06:11:23.028Z 309a0f45-97e5-4094-8d48-d8cc5087f7e4 开始替换变量
> 
> 2020-11-12T06:11:23.029Z 309a0f45-97e5-4094-8d48-d8cc5087f7e4 替换变量完毕
> 
> 2020-11-12T06:11:23.030Z 309a0f45-97e5-4094-8d48-d8cc5087f7e4
> 
> 开始执行脚本签到，请稍等
> 
> 2020-11-12T06:11:23.422Z 309a0f45-97e5-4094-8d48-d8cc5087f7e4 <Buffer 2f 74 6d 70 2f 4a 44 5f 44 61 69 6c 79 42 6f 6e 75 73 2e 6a 73 3a 31 30 35 0a 61 73 79 6e 63 20 66 75 6e 63 74 69 6f 6e 20 61 6c 6c 28 29 20 7b 0a 20 ... 475 more bytes>
> 
> 2020-11-12T06:11:23.423Z 309a0f45-97e5-4094-8d48-d8cc5087f7e4 京东签到脚本执行异常:Error: Command failed: node /tmp/JD_DailyBonus.js >> /tmp/result.txt
> 
> /tmp/JD_DailyBonus.js:105
> 
> async function all() {
> 
>       ^^^^^^^^
> 
> SyntaxError: Unexpected token function
> 
>     at createScript (vm.js:56:10)
> 
>     at Object.runInThisContext (vm.js:97:10)
> 
>     at Module._compile (module.js:549:28)
> 
>     at Object.Module._extensions..js (module.js:586:10)
> 
>     at Module.load (module.js:494:32)
> 
>     at tryModuleLoad (module.js:453:12)
> 
>     at Function.Module._load (module.js:445:3)
> 
>     at Module.runMain (module.js:611:10)
> 
>     at run (bootstrap_node.js:394:7)
> 
>     at startup (bootstrap_node.js:160:9)
> ```

10.x的node版本应该是没事的

**Comment by lxk0301** [comment]
> > > 而且这个文件夹还不用清理
> > 
> > 
> > 云函数把下载的路径和写入路径都改成了再tmp里面。还是有问题
> > ![C3604722-DCA2-4B86-A546-5FAC5A5D7FAA](https://user-images.githubusercontent.com/21308593/98898013-a5a48500-24e7-11eb-9569-66915584b03f.jpeg)
> 
> 下面的代码和node命令里面的路径也要改吧，我看到下面的调用里面没有直接引用这里

等我有空试试看

**Comment by ykrank** [comment]
另外京东摇钱树也需要兼容下
京东摇钱树, 失败! 原因: Error: EROFS: read-only file system, open '/var/user/box.dat'!

**Comment by lxk0301** [comment]
> 另外京东摇钱树也需要兼容下
> 京东摇钱树, 失败! 原因: Error: EROFS: read-only file system, open '/var/user/box.dat'!

已经兼容  


话说虚拟的tmp文件夹，是不是只有新建了层才会有这个玩意？？

![image](https://user-images.githubusercontent.com/21308593/99475533-b3478800-2989-11eb-879e-7bda6fe3bbec.png)
