### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xuelang7009** [lxk0301/jd_scripts#385]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否仔细阅读了教程
- [ ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

Error: Cannot find module '/home/runner/jd_scripts/jd_plantBean.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Error: Process completed with exit code 1.

**Comment by singer1026** [comment]
我的所有的actions从昨天晚上开始就报错了

**Comment by singer1026** [comment]
Run cd ~/jd_scripts
17
internal/modules/cjs/loader.js:883
18
  throw err;
19
  ^
20

21
Error: Cannot find module '/home/runner/jd_scripts/jd_plantBean.js'
22
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
23
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
24
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
25
    at internal/main/run_main_module.js:17:47 {
26
  code: 'MODULE_NOT_FOUND',
27
  requireStack: []
28
}
29
Error: Process completed with exit code 1.

**Comment by singer1026** [comment]
git clone -b master https://gitee.com/lxk0301/jd_scripts.git ~/jd_scripts
yml文件里面修改下git clone ，指定下clone的分支就行了 这样就可以解决了

**Comment by lxk0301** [comment]
action 问题不给予回答
